---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex-k8s-authenticator
  namespace: dex
spec:
  interval: 5m
  chart:
    spec:
      chart: dex-k8s-authenticator
      version: 0.0.2
      sourceRef:
        kind: HelmRepository
        name: dex-k8s-authenticator-charts
        namespace: flux-system
  values:
    image:
      repository: raspbernetes/dex-k8s-authenticator
      tag: latest
    config:
      clusters:
        - name: kubernetes
          short_description: "Kubernetes OCI ARM"
          description: "Kubernetes cluster on Ampere ARM CPU in OCI"
          issuer: https://dex.rand-k8s.ml
          client_id: dex-k8s-authenticator
          client_secret: ZXhhbXBsZS1hcHAtc2VjcmV0
          redirect_uri: https://login.rand-k8s.ml/callback/
          k8s_master_uri: https://k8s-cp:6443
          k8s_ca_pem_base64_encoded: ${KUBE_API_CERT}
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: login.rand-k8s.ml
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: dex-k8s-authenticator-tls
          hosts:
            - login.rand-k8s.ml
    envFrom:
      - secretRef:
              name: dex-github
      - secretRef:
              name: dex-kube-cert    