---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
      - gpg
    state: present

- name: Add Kubernetes apt key.
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  register: add_repository_key
  ignore_errors: "{{ kubernetes_apt_ignore_key_error }}"

# - name: Download kubernetes repo GPG key
#   get_url:
#     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
#     dest: "{{ item }}"
#     mode: '0440'
#   loop: 
#     - /usr/share/keyrings/kubernetes-archive-keyring.gpg
#     - /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg

# - name: Add a key from a file
#   ansible.builtin.apt_key:
#     file: /usr/share/keyrings/kubernetes-archive-keyring.gpg
#     state: present

# - name: Add Kubernetes repository
#   shell: echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list

- name: Add Kubernetes repository.
  apt_repository:
    repo: "{{ kubernetes_apt_repository }}"
    state: present
    filename: kubernetes.list
    #update_cache: true

- name: Run apt-get update
  apt:
    update_cache: yes

- name: Add Kubernetes apt preferences file to pin a version.
  template:
    src: apt-preferences-kubernetes.j2
    dest: /etc/apt/preferences.d/kubernetes
    mode: 0644
