---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart: 
    spec: 
      chart: keycloak
      version: '16.0.x'
      sourceRef:
        name: keycloak-charts
        kind: HelmRepository
        namespace: flux-system
  values:
    ingress:
      enabled: false
      ingressClassName: nginx
      annotations:
      ## Resolve HTTP 502 error using ingress-nginx:
      ## See https://www.ibm.com/support/pages/502-error-ingress-keycloak-response
        nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
      rules:
        - host: keycloak.rand-k8s.ml
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
           - keycloak.rand-k8s.ml
          secretName: keycloak-cert-secret
    serviceMonitor:
      enables: true
      namespace: monitoring
      labels:
        release: monitoring
    extraEnv: |
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_STATISTICS
        value: all
    extraEnvFrom: |
      - secretRef:
          name: '{{ include "keycloak.fullname" . }}-admin'
    secrets:
      admin:
        stringData:
          KEYCLOAK_USER: admin    
          KEYCLOAK_PASSWORD: keycloak
    prometheusRule:
      enabled: true
      namespace: monitoring
      labels:
        release: monitoring
        app: kube-prometheus-stack
      rules:
        - alert: keycloak-IngressHigh5xxRate
          annotations:
            message: The percentage of 5xx errors for keycloak over the last 5 minutes is over 1%.
          expr: |
            (
              sum(
                rate(
                  nginx_ingress_controller_response_duration_seconds_count{exported_namespace="mynamespace",ingress="mynamespace-keycloak",status=~"5[0-9]{2}"}[1m]
                )
              )
              /
              sum(
                rate(
                  nginx_ingress_controller_response_duration_seconds_count{exported_namespace="mynamespace",ingress="mynamespace-keycloak"}[1m]
                )
              )
            ) * 100 > 1
          for: 5m
          labels:
            severity: warning
