apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  interval: 5m
  chart: 
    spec: 
      chart: gitlab-runner
      version: '0.35.x'
      sourceRef:
        name: gitlab-runner-charts
        kind: HelmRepository
        namespace: flux-system
  values:
    gitlabUrl: https://gitlab.com
    rbac:
      create: true
      clusterWideAccess: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      enabled: true
    runners:
      config: |
        [[runners]]
          [runners.kubernetes]
            namespace = "gitlab-runner"
            image = "ubuntu:20.04"
            privileged = true
          [runners.kubernetes.node_selector]
            "kubernetes.io/arch" = "arm64"
            "kubernetes.io/os" = "linux"
      locked: false
      tags: "arm64,linux,oci-k8s,kubernetes"
      helpers:
        image: "gitlab/gitlab-runner-helper:ubuntu-arm64-latest"
  valuesFrom:
    - kind: Secret
      name: gitlab-runner-registration-token
      valuesKey: runnerRegistrationToken
      targetPath: runnerRegistrationToken
