---
k8s_manifests: 
  - dir: local-path-provisioner
    lookup_type: 'file'
k8s_manifests_base_dir: k8s-manifests/
k8s_manifests_state: present
k8s_force: false

k8s_resource_namespace: ''
k8s_manage_namespace: false
k8s_no_log: false
k8s_manifests_namespaces:
  - local-path-storage
  - kube-system
 