apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: web-app-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://gitlab.com/api/v4/projects/29436006/packages/helm/stable
  secretRef:
    name: gitlab-token
