apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: web-app
  namespace: web-app
spec:
  interval: 5m
  chart: 
    spec: 
      chart: web-app
      version: '0.1.x'
      sourceRef:
        name: web-app-charts
        kind: HelmRepository
        namespace: flux-system
  values:
    image:
      tag: 5421e70b
    imagePullSecrets:
      - name: github-registry
    service:
      port: 8000
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
      hosts:
        - host: app.rand-k8s.ml
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: web-app-cert-secret
          hosts:
            - app.rand-k8s.ml
      
