---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-policy-agent-gatekeeper
  namespace: opa-gatekeeper
spec:
  interval: 5m
  chart:
    spec:
      chart: gatekeeper
      version: 3.7.0
      sourceRef:
        kind: HelmRepository
        name: open-policy-agent-gatekeeper-charts
        namespace: flux-system
  values:
    replicas: 1