apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx
  - kube-prometheus-stack
  - gitlab-runner
  - namespaces
  - metrics-server
  - cert-manager
  - oauth2-proxy
  #- keycloak
  - dex
  - dex-k8s-authenticator
  - open-policy-agent-gatekeeper