---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  interval: 5m
  chart:
    spec:
      chart: dex
      version: 0.6.3
      sourceRef:
        kind: HelmRepository
        name: dex-charts
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: dex.rand-k8s.ml
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: dex-tls
          hosts:
            - dex.rand-k8s.ml
    config:
      issuer: https://dex.rand-k8s.ml
      storage: 
        type: kubernetes
        config:
          inCluster: true
      oauth2:
        responseTypes: ["code", "token", "id_token"]
        skipApprovalScreen: true
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $GITHUB_CLIENT_ID
            clientSecret: $GITHUB_CLIENT_SECRET
            redirectURI: https://dex.rand-k8s.ml/callback
      staticClients:
        - id: dex-k8s-authenticator
          name: dex-k8s-authenticator
          secret: ZXhhbXBsZS1hcHAtc2VjcmV0
          redirectURIs:
            - https://login.rand-k8s.ml/callback/
    envFrom:
      - secretRef:
              name: dex-github