apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flux.rules
  namespace: monitoring
  labels:
    release: monitoring
    app: kube-prometheus-stack
spec:
  groups:
    - name: GitOpsToolkit
      rules:
        - alert: ReconciliationFailure
          expr: max(gotk_reconcile_condition{status="False",type="Ready"}) by (exported_namespace, name, kind) + on(exported_namespace, name, kind) (max(gotk_reconcile_condition{status="Deleted"}) by (exported_namespace, name, kind)) * 2 == 1
          for: 10m
          labels:
            severity: page
          annotations:
            summary: '{{ $labels.kind }} {{ $labels.exported_namespace }}/{{ $labels.name }} reconciliation has been failing for more than ten minutes.'

