all:
  children:
    k8s_control_plane:
      hosts:
        k8s-cp:
          ansible_host: 130.61.109.143
    k8s_workers:
      hosts:
        k8s-worker1:
          ansible_host: 130.61.21.92
        k8s-worker2:
          ansible_host: 130.61.23.87
    k8s_cluster:
      children:
        k8s_control_plane:
        k8s_workers: