all:
  children:
    k8s_control_plane:
      hosts:
        k8s-cp:
          ansible_host: 130.61.168.105
    k8s_workers:
      hosts:
        k8s-worker1:
          ansible_host: 130.61.213.75
        k8s-worker2:
          ansible_host: 130.61.137.151
    k8s_cluster:
      children:
        k8s_control_plane:
        k8s_workers: