all:
  children:
    k8s_control_plane:
      hosts:
        k8s-cp:
          ansible_host: 130.61.78.94
    k8s_workers:
      hosts:
        k8s-worker1:
          ansible_host: 130.61.26.120
        k8s-worker2:
          ansible_host: 130.61.218.130
    k8s_cluster:
      children:
        k8s_control_plane:
        k8s_workers: