#ansible_host: 192.168.1.220
#ansible_user: vagrant
#ansible_ssh_private_key_file: "./.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"
ansible_host: 127.0.0.1
ansible_user: ubuntu
ansible_port: 2222
ansible_ssh_private_key_file: "~/ya_rsa"


###################### Kubernetes variable ############################################
vpn_ip_address: 172.16.10.2
kubernetes_role: "control_plane"
kubernetes_kubeproxy_mode: "ipvs"
kubernetes_apiserver_advertise_address: "{{ ansible_host }}"
kubernetes_cluster_domain_name: "cluster.local"
kubernetes_cgroupDriver: "systemd"
kubernetes_cri_socket: "/run/containerd/containerd.sock"
kubernetes_cluster_name: kubernetes
kubernetes_apiserver_certSANs:
  - 172.16.10.2
  - cluster-api.rand-k8s.tk
  - rand-k8s.tk
  - k8s-cp.k8ssubnet.internal.oraclevcn.com
  - k8s-worker1
  - k8s-worker2
  - k8s-cp
