---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - monitoring.yaml
  - web-app.yaml
  - ingress-nginx.yaml
  - keycloak.yaml
  #- oauth2-proxy.yaml
  - dex.yaml
  - opa-gatekeeper.yaml
